### ISSUE TITLE
default on/off variations for JSON type

### ISSUE THREAD

**Issue by yutsengwei** [launchdarkly/terraform-provider-launchdarkly#42]
Hello, is there any document to set the default variation for JSON type? I only find boolean and string type. Thank you so much

**Comment by ldhenry** [comment]
Hello @yutsengwei, thanks for the feedback, it seems our documentation is quite sparse in this area. I'll work on improving this and I will not close this issue until our documentation is improved. In the meantime, here are some examples of of how to set default JSON variations:

If your goal is to set the global `default_on_varation` and `default_off_variation` for a feature flag, use the `launchdarkly_feature_flag` resource as follows:
``` hcl
resource "launchdarkly_feature_flag" "json" {
  project_key    = "test"
  key            = "json-flag"
  name           = "JSON flag"
  variation_type = "json"

  variations {
    value = jsonencode({ "foo" : "bar" })
  }
  variations {
    value = jsonencode({ "bar" : "foo", "bars" : "foos" })
  }

  default_on_variation = jsonencode({ "bar" : "foo", "bars" : "foos" })

  default_off_variation = jsonencode({ "foo" : "bar" })
}
```
**Note:** `default_on_variation` and `default_off_variation` values must be exact matches to the `variations` `value` (including whitespace). For this reason, I used the [`jsonencode` function](https://www.terraform.io/docs/configuration/functions/jsonencode.html), but you may be able to further clean the config up using variables.

It should also be noted that the above configuration only specifies  the default variations for new environments, and will not change the default variations for existing environments. If you want to set the default variations in a specific environment, use the `flag_fallthrough` and `off_variation` arguments in the `launchdarkly_feature_flag_environment` resource. as follows:

``` hcl
resource "launchdarkly_feature_flag_environment" "json_defaults" {
  flag_id = launchdarkly_feature_flag.json.id
  env_key = "production"

  flag_fallthrough {
    variation = 1
  }

  off_variation = 0
}
```
Both `flag_fallthrough` and `off_variation` use the variation *index* instead of the variation *value*.

Please let me know if you need any additional clarification on this.

Thanks,
Henry

**Comment by yutsengwei** [comment]
thanks for the information

**Comment by ldhenry** [comment]
Closing this issue now since the docs have been updated with an example similar to what I posted above. Please let me know if you need any additional help.

https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/feature_flag
