### ISSUE TITLE
Terraform 0.13 - Unable to configure provider

### ISSUE THREAD

**Issue by masonhuemmer** [launchdarkly/terraform-provider-launchdarkly#47]
I am receiving the following error. 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/49791141/102106884-b9991a80-3df6-11eb-876a-be3f638da319.png">

Below is my configuration file for setting the provider. Just in case you are not aware, this is the new way to configure providers for 0.13. I did try setting the provider based on the requirements for 0.12 and below and still received the same error.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/49791141/102106945-c9186380-3df6-11eb-8356-57423048b789.png">

**Comment by ldhenry** [comment]
Hey @masonhuemmer,

Thanks for bringing this to our attention. We were unaware that there was an issue with Terraform 0.13. We're looking into this now and will keep this issue updated as we learn more.

Thanks,
Henry

**Comment by masonhuemmer** [comment]
I would like to mention that I experienced the same issue when I set the source to “launchdarkly/launchdarkly”.

**Comment by sloloris** [comment]
Hi @masonhuemmer, I was able to reproduce your error on Terraform version 0.13.2 with this configuration:
```hcl
terraform {
  required_providers {
    launchdarkly = {
      source  = "hashicorp/launchdarkly"
      version = "~> 1.5"
    }
  }
}
```
I then updated the source to `"launchdarkly/launchdarkly"` and followed the instructions to run `terraform 0.13upgrade .`, which added `required_version` so that my config looked like this:
```hcl
terraform {
  required_providers {
    launchdarkly = {
      source  = "launchdarkly/launchdarkly"
      version = "~> 1.5"
    }
  }
  required_version = ">= 0.13"
}
```
and was able to init, plan, and apply without issue. If you are still experiencing this issue would you mind giving me some more background on the specific Terraform version you are using and the `terraform` block variations you have tried that are continuing to produce this error? I'm afraid I've otherwise hit a bit of a dead end in my investigations.

**Comment by sloloris** [comment]
Hi @masonhuemmer! I realize that my response came at a time when a lot of people were on holiday, so I just wanted to check in and see if you've managed to resolve this issue. If I don't hear from you otherwise in the next few days, I will close the issue. I wish you a lovely start to the new year!
